/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EnergyLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const AddFeedbackRequest = IDL.Record({
  'energy_level' : EnergyLevel,
  'date' : IDL.Text,
  'health_status' : IDL.Text,
  'notes' : IDL.Text,
  'feedback_text' : IDL.Text,
});
export const UserFeedback = IDL.Record({
  'id' : IDL.Nat,
  'energy_level' : EnergyLevel,
  'date' : IDL.Text,
  'created_at' : IDL.Int,
  'user_id' : IDL.Principal,
  'health_status' : IDL.Text,
  'notes' : IDL.Text,
  'feedback_text' : IDL.Text,
});
export const FeedbackResult = IDL.Variant({
  'ok' : UserFeedback,
  'error' : IDL.Text,
  'alreadySubmitted' : UserFeedback,
});
export const ChatRequest = IDL.Record({ 'user_message' : IDL.Text });
export const ChatResponse = IDL.Record({
  'ai_message' : IDL.Text,
  'is_health_response' : IDL.Bool,
});
export const ChatResult = IDL.Variant({
  'ok' : ChatResponse,
  'tierLimited' : IDL.Text,
  'error' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const JourneyCompletionRequest = IDL.Record({
  'task_id' : IDL.Nat,
  'date' : Timestamp,
});
export const JourneyProgress = IDL.Record({
  'streak_days' : IDL.Nat,
  'completed_task_ids' : IDL.Vec(IDL.Nat),
  'date' : Timestamp,
  'earned_xp' : IDL.Nat,
});
export const CreateOrderResponse = IDL.Record({
  'currency' : IDL.Text,
  'order_id' : IDL.Text,
  'amount' : IDL.Nat,
});
export const EditMealRequest = IDL.Record({
  'task_id' : IDL.Text,
  'quantity' : IDL.Text,
  'food_items' : IDL.Vec(IDL.Text),
});
export const JourneyTaskType = IDL.Variant({
  'meal' : IDL.Null,
  'water' : IDL.Null,
});
export const JourneyTask = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'calories' : IDL.Nat,
  'name' : IDL.Text,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'xp_reward' : IDL.Nat,
  'quantity' : IDL.Text,
  'task_type' : JourneyTaskType,
  'time_label' : IDL.Text,
  'food_items' : IDL.Vec(IDL.Text),
  'protein' : IDL.Nat,
});
export const DailyJourney = IDL.Record({
  'id' : IDL.Text,
  'generated_by_ai' : IDL.Bool,
  'tasks' : IDL.Vec(JourneyTask),
  'date' : Timestamp,
  'total_xp' : IDL.Nat,
});
export const EditableMeal = IDL.Record({
  'id' : IDL.Nat,
  'calories' : IDL.Nat,
  'name' : IDL.Text,
  'time' : IDL.Text,
  'quantity' : IDL.Text,
  'task_type' : JourneyTaskType,
  'food_items' : IDL.Vec(IDL.Text),
  'protein' : IDL.Nat,
});
export const EditMealPlanRequest = IDL.Record({
  'meals' : IDL.Vec(EditableMeal),
});
export const GeneratePlanResult = IDL.Variant({
  'ok' : DailyJourney,
  'tierLimited' : IDL.Text,
  'error' : IDL.Text,
});
export const AdminStats = IDL.Record({
  'total_users' : IDL.Nat,
  'premium_users' : IDL.Nat,
  'active_users' : IDL.Nat,
  'total_waitlist' : IDL.Nat,
});
export const MissedMealEntry = IDL.Record({
  'meal_type' : IDL.Text,
  'reason' : IDL.Text,
});
export const UserActivity = IDL.Record({
  'protein_intake' : IDL.Opt(IDL.Float64),
  'daily_calories' : IDL.Opt(IDL.Nat),
  'date' : Timestamp,
  'water_intake' : IDL.Opt(IDL.Float64),
  'user_id' : IDL.Principal,
  'total_protein' : IDL.Opt(IDL.Float64),
  'meals_skipped' : IDL.Opt(IDL.Nat),
  'missed_meals' : IDL.Opt(IDL.Vec(MissedMealEntry)),
  'meals_completed' : IDL.Opt(IDL.Nat),
});
export const TransactionType = IDL.Variant({
  'reward' : IDL.Null,
  'deduction' : IDL.Null,
  'recharge' : IDL.Null,
});
export const BalanceTransaction = IDL.Record({
  'id' : IDL.Text,
  'balance_after' : IDL.Float64,
  'transaction_type' : TransactionType,
  'date' : Timestamp,
  'user_id' : IDL.Principal,
  'amount' : IDL.Float64,
  'reason' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'refunded' : IDL.Null,
  'success' : IDL.Null,
  'failed' : IDL.Null,
});
export const SubscriptionPlan = IDL.Variant({
  'premium' : IDL.Null,
  'free' : IDL.Null,
});
export const Payment = IDL.Record({
  'status' : PaymentStatus,
  'date' : Timestamp,
  'plan' : IDL.Opt(SubscriptionPlan),
  'user_id' : IDL.Principal,
  'order_id' : IDL.Text,
  'payment_id' : IDL.Text,
  'amount' : IDL.Nat,
});
export const DietaryPreference = IDL.Variant({
  'non_vegetarian' : IDL.Null,
  'vegetarian' : IDL.Null,
});
export const Goal = IDL.Variant({
  'muscle_gain' : IDL.Null,
  'lifestyle_balance' : IDL.Null,
  'fat_loss' : IDL.Null,
});
export const PlanStatus = IDL.Variant({
  'trial' : IDL.Null,
  'premium' : IDL.Null,
  'free' : IDL.Null,
});
export const ActivityLevel = IDL.Variant({
  'intense' : IDL.Null,
  'light' : IDL.Null,
  'sedentary' : IDL.Null,
  'moderate' : IDL.Null,
});
export const DietType = IDL.Variant({ 'veg' : IDL.Null, 'non_veg' : IDL.Null });
export const UserPublic = IDL.Record({
  'id' : IDL.Principal,
  'age' : IDL.Nat,
  'weight' : IDL.Opt(IDL.Float64),
  'height' : IDL.Opt(IDL.Float64),
  'balance' : IDL.Float64,
  'lifestyle_description' : IDL.Opt(IDL.Text),
  'dietary_preference' : DietaryPreference,
  'goal' : IDL.Opt(Goal),
  'name' : IDL.Text,
  'created_at' : Timestamp,
  'email' : IDL.Text,
  'plan_status' : PlanStatus,
  'activity_level' : ActivityLevel,
  'subscription_plan' : SubscriptionPlan,
  'diet_type' : DietType,
  'trial_start_date' : IDL.Opt(Timestamp),
});
export const LeaderboardEntry = IDL.Record({
  'streak_days' : IDL.Nat,
  'is_current_user' : IDL.Bool,
  'rank' : IDL.Nat,
  'weekly_xp' : IDL.Nat,
  'display_name' : IDL.Text,
});
export const StreakLeaderboard = IDL.Record({
  'current_user_entry' : IDL.Opt(LeaderboardEntry),
  'top_entries' : IDL.Vec(LeaderboardEntry),
});
export const DailyBalanceSummary = IDL.Record({
  'date' : IDL.Text,
  'balance_end' : IDL.Float64,
  'rewards_total' : IDL.Float64,
  'deductions_total' : IDL.Float64,
});
export const WeeklyBalanceReport = IDL.Record({
  'total_reward_events' : IDL.Nat,
  'total_deduction_events' : IDL.Nat,
  'week_net_change' : IDL.Float64,
  'daily_summaries' : IDL.Vec(DailyBalanceSummary),
});
export const WebhookPayload = IDL.Record({
  'status' : PaymentStatus,
  'user_id' : IDL.Principal,
  'order_id' : IDL.Text,
  'payment_id' : IDL.Text,
  'amount' : IDL.Nat,
});
export const AuthResponse = IDL.Record({
  'user_id' : IDL.Principal,
  'session_token' : IDL.Text,
});
export const RegisterUserRequest = IDL.Record({
  'age' : IDL.Nat,
  'weight' : IDL.Opt(IDL.Float64),
  'height' : IDL.Opt(IDL.Float64),
  'lifestyle_description' : IDL.Opt(IDL.Text),
  'dietary_preference' : DietaryPreference,
  'goal' : IDL.Opt(Goal),
  'password' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'activity_level' : ActivityLevel,
  'diet_type' : IDL.Opt(DietType),
});
export const UpdateUserRequest = IDL.Record({
  'age' : IDL.Opt(IDL.Nat),
  'weight' : IDL.Opt(IDL.Float64),
  'height' : IDL.Opt(IDL.Float64),
  'balance' : IDL.Opt(IDL.Float64),
  'lifestyle_description' : IDL.Opt(IDL.Text),
  'dietary_preference' : IDL.Opt(DietaryPreference),
  'goal' : IDL.Opt(Goal),
  'name' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'plan_status' : IDL.Opt(PlanStatus),
  'activity_level' : IDL.Opt(ActivityLevel),
  'diet_type' : IDL.Opt(DietType),
});
export const VerifyPaymentRequest = IDL.Record({
  'order_id' : IDL.Text,
  'razorpay_signature' : IDL.Text,
  'payment_id' : IDL.Text,
});

export const idlService = IDL.Service({
  'addFeedback' : IDL.Func(
      [IDL.Text, AddFeedbackRequest],
      [FeedbackResult],
      [],
    ),
  'chatWithAI' : IDL.Func([IDL.Text, ChatRequest], [ChatResult], []),
  'completeJourneyTask' : IDL.Func(
      [IDL.Text, JourneyCompletionRequest],
      [IDL.Variant({ 'ok' : JourneyProgress, 'err' : IDL.Text })],
      [],
    ),
  'createRazorpayOrder' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : CreateOrderResponse, 'err' : IDL.Text })],
      [],
    ),
  'editAIMeal' : IDL.Func(
      [IDL.Text, EditMealRequest],
      [IDL.Variant({ 'ok' : DailyJourney, 'err' : IDL.Text })],
      [],
    ),
  'editMealPlan' : IDL.Func(
      [IDL.Text, EditMealPlanRequest],
      [IDL.Variant({ 'ok' : DailyJourney, 'err' : IDL.Text })],
      [],
    ),
  'generateAIDiet' : IDL.Func([IDL.Text], [GeneratePlanResult], []),
  'generateTodayPlan' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : DailyJourney, 'err' : IDL.Text })],
      [],
    ),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getFeedbackHistory' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(UserFeedback)],
      ['query'],
    ),
  'getMyActivity' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(UserActivity), 'err' : IDL.Text })],
      ['query'],
    ),
  'getMyBalance' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Float64, 'err' : IDL.Text })],
      ['query'],
    ),
  'getMyBalanceHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(BalanceTransaction), 'err' : IDL.Text })],
      ['query'],
    ),
  'getMyLatestActivity' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Opt(UserActivity), 'err' : IDL.Text })],
      ['query'],
    ),
  'getMyPayments' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(Payment), 'err' : IDL.Text })],
      ['query'],
    ),
  'getMyProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
      [],
    ),
  'getStreakLeaderboard' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : StreakLeaderboard, 'err' : IDL.Text })],
      ['query'],
    ),
  'getTodayFeedback' : IDL.Func([IDL.Text], [IDL.Opt(UserFeedback)], ['query']),
  'getTodayJourney' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : DailyJourney, 'err' : IDL.Text })],
      [],
    ),
  'getTodayProgress' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : JourneyProgress, 'err' : IDL.Text })],
      ['query'],
    ),
  'getWaitlistCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getWeeklyBalanceReport' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : WeeklyBalanceReport, 'err' : IDL.Text })],
      ['query'],
    ),
  'handlePaymentWebhook' : IDL.Func([WebhookPayload], [IDL.Bool], []),
  'joinWaitlist' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'alreadyExists' : IDL.Null })],
      [],
    ),
  'logDailyActivity' : IDL.Func(
      [IDL.Text, UserActivity],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'logMissedMeal' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'loginUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : AuthResponse, 'err' : IDL.Text })],
      [],
    ),
  'logoutUser' : IDL.Func([IDL.Text], [], []),
  'processDayEndAccountability' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Float64, 'err' : IDL.Text })],
      [],
    ),
  'rechargeBalance' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : CreateOrderResponse, 'err' : IDL.Text })],
      [],
    ),
  'registerUser' : IDL.Func(
      [RegisterUserRequest],
      [IDL.Variant({ 'ok' : AuthResponse, 'err' : IDL.Text })],
      [],
    ),
  'resetToAIPlan' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : DailyJourney, 'err' : IDL.Text })],
      [],
    ),
  'skipJourneyTask' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'balance' : IDL.Float64,
            'deducted' : IDL.Bool,
            'balance_empty' : IDL.Bool,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'updateMyProfile' : IDL.Func(
      [IDL.Text, UpdateUserRequest],
      [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
      [],
    ),
  'verifyRazorpayPayment' : IDL.Func(
      [IDL.Text, VerifyPaymentRequest],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'verifyRechargePayment' : IDL.Func(
      [IDL.Text, VerifyPaymentRequest, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Float64, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EnergyLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const AddFeedbackRequest = IDL.Record({
    'energy_level' : EnergyLevel,
    'date' : IDL.Text,
    'health_status' : IDL.Text,
    'notes' : IDL.Text,
    'feedback_text' : IDL.Text,
  });
  const UserFeedback = IDL.Record({
    'id' : IDL.Nat,
    'energy_level' : EnergyLevel,
    'date' : IDL.Text,
    'created_at' : IDL.Int,
    'user_id' : IDL.Principal,
    'health_status' : IDL.Text,
    'notes' : IDL.Text,
    'feedback_text' : IDL.Text,
  });
  const FeedbackResult = IDL.Variant({
    'ok' : UserFeedback,
    'error' : IDL.Text,
    'alreadySubmitted' : UserFeedback,
  });
  const ChatRequest = IDL.Record({ 'user_message' : IDL.Text });
  const ChatResponse = IDL.Record({
    'ai_message' : IDL.Text,
    'is_health_response' : IDL.Bool,
  });
  const ChatResult = IDL.Variant({
    'ok' : ChatResponse,
    'tierLimited' : IDL.Text,
    'error' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const JourneyCompletionRequest = IDL.Record({
    'task_id' : IDL.Nat,
    'date' : Timestamp,
  });
  const JourneyProgress = IDL.Record({
    'streak_days' : IDL.Nat,
    'completed_task_ids' : IDL.Vec(IDL.Nat),
    'date' : Timestamp,
    'earned_xp' : IDL.Nat,
  });
  const CreateOrderResponse = IDL.Record({
    'currency' : IDL.Text,
    'order_id' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const EditMealRequest = IDL.Record({
    'task_id' : IDL.Text,
    'quantity' : IDL.Text,
    'food_items' : IDL.Vec(IDL.Text),
  });
  const JourneyTaskType = IDL.Variant({
    'meal' : IDL.Null,
    'water' : IDL.Null,
  });
  const JourneyTask = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'calories' : IDL.Nat,
    'name' : IDL.Text,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'xp_reward' : IDL.Nat,
    'quantity' : IDL.Text,
    'task_type' : JourneyTaskType,
    'time_label' : IDL.Text,
    'food_items' : IDL.Vec(IDL.Text),
    'protein' : IDL.Nat,
  });
  const DailyJourney = IDL.Record({
    'id' : IDL.Text,
    'generated_by_ai' : IDL.Bool,
    'tasks' : IDL.Vec(JourneyTask),
    'date' : Timestamp,
    'total_xp' : IDL.Nat,
  });
  const EditableMeal = IDL.Record({
    'id' : IDL.Nat,
    'calories' : IDL.Nat,
    'name' : IDL.Text,
    'time' : IDL.Text,
    'quantity' : IDL.Text,
    'task_type' : JourneyTaskType,
    'food_items' : IDL.Vec(IDL.Text),
    'protein' : IDL.Nat,
  });
  const EditMealPlanRequest = IDL.Record({ 'meals' : IDL.Vec(EditableMeal) });
  const GeneratePlanResult = IDL.Variant({
    'ok' : DailyJourney,
    'tierLimited' : IDL.Text,
    'error' : IDL.Text,
  });
  const AdminStats = IDL.Record({
    'total_users' : IDL.Nat,
    'premium_users' : IDL.Nat,
    'active_users' : IDL.Nat,
    'total_waitlist' : IDL.Nat,
  });
  const MissedMealEntry = IDL.Record({
    'meal_type' : IDL.Text,
    'reason' : IDL.Text,
  });
  const UserActivity = IDL.Record({
    'protein_intake' : IDL.Opt(IDL.Float64),
    'daily_calories' : IDL.Opt(IDL.Nat),
    'date' : Timestamp,
    'water_intake' : IDL.Opt(IDL.Float64),
    'user_id' : IDL.Principal,
    'total_protein' : IDL.Opt(IDL.Float64),
    'meals_skipped' : IDL.Opt(IDL.Nat),
    'missed_meals' : IDL.Opt(IDL.Vec(MissedMealEntry)),
    'meals_completed' : IDL.Opt(IDL.Nat),
  });
  const TransactionType = IDL.Variant({
    'reward' : IDL.Null,
    'deduction' : IDL.Null,
    'recharge' : IDL.Null,
  });
  const BalanceTransaction = IDL.Record({
    'id' : IDL.Text,
    'balance_after' : IDL.Float64,
    'transaction_type' : TransactionType,
    'date' : Timestamp,
    'user_id' : IDL.Principal,
    'amount' : IDL.Float64,
    'reason' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'refunded' : IDL.Null,
    'success' : IDL.Null,
    'failed' : IDL.Null,
  });
  const SubscriptionPlan = IDL.Variant({
    'premium' : IDL.Null,
    'free' : IDL.Null,
  });
  const Payment = IDL.Record({
    'status' : PaymentStatus,
    'date' : Timestamp,
    'plan' : IDL.Opt(SubscriptionPlan),
    'user_id' : IDL.Principal,
    'order_id' : IDL.Text,
    'payment_id' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const DietaryPreference = IDL.Variant({
    'non_vegetarian' : IDL.Null,
    'vegetarian' : IDL.Null,
  });
  const Goal = IDL.Variant({
    'muscle_gain' : IDL.Null,
    'lifestyle_balance' : IDL.Null,
    'fat_loss' : IDL.Null,
  });
  const PlanStatus = IDL.Variant({
    'trial' : IDL.Null,
    'premium' : IDL.Null,
    'free' : IDL.Null,
  });
  const ActivityLevel = IDL.Variant({
    'intense' : IDL.Null,
    'light' : IDL.Null,
    'sedentary' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const DietType = IDL.Variant({ 'veg' : IDL.Null, 'non_veg' : IDL.Null });
  const UserPublic = IDL.Record({
    'id' : IDL.Principal,
    'age' : IDL.Nat,
    'weight' : IDL.Opt(IDL.Float64),
    'height' : IDL.Opt(IDL.Float64),
    'balance' : IDL.Float64,
    'lifestyle_description' : IDL.Opt(IDL.Text),
    'dietary_preference' : DietaryPreference,
    'goal' : IDL.Opt(Goal),
    'name' : IDL.Text,
    'created_at' : Timestamp,
    'email' : IDL.Text,
    'plan_status' : PlanStatus,
    'activity_level' : ActivityLevel,
    'subscription_plan' : SubscriptionPlan,
    'diet_type' : DietType,
    'trial_start_date' : IDL.Opt(Timestamp),
  });
  const LeaderboardEntry = IDL.Record({
    'streak_days' : IDL.Nat,
    'is_current_user' : IDL.Bool,
    'rank' : IDL.Nat,
    'weekly_xp' : IDL.Nat,
    'display_name' : IDL.Text,
  });
  const StreakLeaderboard = IDL.Record({
    'current_user_entry' : IDL.Opt(LeaderboardEntry),
    'top_entries' : IDL.Vec(LeaderboardEntry),
  });
  const DailyBalanceSummary = IDL.Record({
    'date' : IDL.Text,
    'balance_end' : IDL.Float64,
    'rewards_total' : IDL.Float64,
    'deductions_total' : IDL.Float64,
  });
  const WeeklyBalanceReport = IDL.Record({
    'total_reward_events' : IDL.Nat,
    'total_deduction_events' : IDL.Nat,
    'week_net_change' : IDL.Float64,
    'daily_summaries' : IDL.Vec(DailyBalanceSummary),
  });
  const WebhookPayload = IDL.Record({
    'status' : PaymentStatus,
    'user_id' : IDL.Principal,
    'order_id' : IDL.Text,
    'payment_id' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const AuthResponse = IDL.Record({
    'user_id' : IDL.Principal,
    'session_token' : IDL.Text,
  });
  const RegisterUserRequest = IDL.Record({
    'age' : IDL.Nat,
    'weight' : IDL.Opt(IDL.Float64),
    'height' : IDL.Opt(IDL.Float64),
    'lifestyle_description' : IDL.Opt(IDL.Text),
    'dietary_preference' : DietaryPreference,
    'goal' : IDL.Opt(Goal),
    'password' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'activity_level' : ActivityLevel,
    'diet_type' : IDL.Opt(DietType),
  });
  const UpdateUserRequest = IDL.Record({
    'age' : IDL.Opt(IDL.Nat),
    'weight' : IDL.Opt(IDL.Float64),
    'height' : IDL.Opt(IDL.Float64),
    'balance' : IDL.Opt(IDL.Float64),
    'lifestyle_description' : IDL.Opt(IDL.Text),
    'dietary_preference' : IDL.Opt(DietaryPreference),
    'goal' : IDL.Opt(Goal),
    'name' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'plan_status' : IDL.Opt(PlanStatus),
    'activity_level' : IDL.Opt(ActivityLevel),
    'diet_type' : IDL.Opt(DietType),
  });
  const VerifyPaymentRequest = IDL.Record({
    'order_id' : IDL.Text,
    'razorpay_signature' : IDL.Text,
    'payment_id' : IDL.Text,
  });
  
  return IDL.Service({
    'addFeedback' : IDL.Func(
        [IDL.Text, AddFeedbackRequest],
        [FeedbackResult],
        [],
      ),
    'chatWithAI' : IDL.Func([IDL.Text, ChatRequest], [ChatResult], []),
    'completeJourneyTask' : IDL.Func(
        [IDL.Text, JourneyCompletionRequest],
        [IDL.Variant({ 'ok' : JourneyProgress, 'err' : IDL.Text })],
        [],
      ),
    'createRazorpayOrder' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : CreateOrderResponse, 'err' : IDL.Text })],
        [],
      ),
    'editAIMeal' : IDL.Func(
        [IDL.Text, EditMealRequest],
        [IDL.Variant({ 'ok' : DailyJourney, 'err' : IDL.Text })],
        [],
      ),
    'editMealPlan' : IDL.Func(
        [IDL.Text, EditMealPlanRequest],
        [IDL.Variant({ 'ok' : DailyJourney, 'err' : IDL.Text })],
        [],
      ),
    'generateAIDiet' : IDL.Func([IDL.Text], [GeneratePlanResult], []),
    'generateTodayPlan' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : DailyJourney, 'err' : IDL.Text })],
        [],
      ),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getFeedbackHistory' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(UserFeedback)],
        ['query'],
      ),
    'getMyActivity' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(UserActivity), 'err' : IDL.Text })],
        ['query'],
      ),
    'getMyBalance' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Float64, 'err' : IDL.Text })],
        ['query'],
      ),
    'getMyBalanceHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(BalanceTransaction), 'err' : IDL.Text })],
        ['query'],
      ),
    'getMyLatestActivity' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Opt(UserActivity), 'err' : IDL.Text })],
        ['query'],
      ),
    'getMyPayments' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(Payment), 'err' : IDL.Text })],
        ['query'],
      ),
    'getMyProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
        [],
      ),
    'getStreakLeaderboard' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : StreakLeaderboard, 'err' : IDL.Text })],
        ['query'],
      ),
    'getTodayFeedback' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserFeedback)],
        ['query'],
      ),
    'getTodayJourney' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : DailyJourney, 'err' : IDL.Text })],
        [],
      ),
    'getTodayProgress' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : JourneyProgress, 'err' : IDL.Text })],
        ['query'],
      ),
    'getWaitlistCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getWeeklyBalanceReport' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : WeeklyBalanceReport, 'err' : IDL.Text })],
        ['query'],
      ),
    'handlePaymentWebhook' : IDL.Func([WebhookPayload], [IDL.Bool], []),
    'joinWaitlist' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'alreadyExists' : IDL.Null })],
        [],
      ),
    'logDailyActivity' : IDL.Func(
        [IDL.Text, UserActivity],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'logMissedMeal' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'loginUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : AuthResponse, 'err' : IDL.Text })],
        [],
      ),
    'logoutUser' : IDL.Func([IDL.Text], [], []),
    'processDayEndAccountability' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Float64, 'err' : IDL.Text })],
        [],
      ),
    'rechargeBalance' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : CreateOrderResponse, 'err' : IDL.Text })],
        [],
      ),
    'registerUser' : IDL.Func(
        [RegisterUserRequest],
        [IDL.Variant({ 'ok' : AuthResponse, 'err' : IDL.Text })],
        [],
      ),
    'resetToAIPlan' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : DailyJourney, 'err' : IDL.Text })],
        [],
      ),
    'skipJourneyTask' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'balance' : IDL.Float64,
              'deducted' : IDL.Bool,
              'balance_empty' : IDL.Bool,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'updateMyProfile' : IDL.Func(
        [IDL.Text, UpdateUserRequest],
        [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
        [],
      ),
    'verifyRazorpayPayment' : IDL.Func(
        [IDL.Text, VerifyPaymentRequest],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'verifyRechargePayment' : IDL.Func(
        [IDL.Text, VerifyPaymentRequest, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Float64, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };