/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActivityLevel = { 'intense' : null } |
  { 'light' : null } |
  { 'sedentary' : null } |
  { 'moderate' : null };
export interface AddFeedbackRequest {
  'energy_level' : EnergyLevel,
  'date' : string,
  'health_status' : string,
  'notes' : string,
  'feedback_text' : string,
}
export interface AdminStats {
  'total_users' : bigint,
  'premium_users' : bigint,
  'active_users' : bigint,
  'total_waitlist' : bigint,
}
export interface AuthResponse {
  'user_id' : Principal,
  'session_token' : string,
}
export interface BalanceTransaction {
  'id' : string,
  'balance_after' : number,
  'transaction_type' : TransactionType,
  'date' : Timestamp,
  'user_id' : Principal,
  'amount' : number,
  'reason' : string,
}
export interface ChatRequest { 'user_message' : string }
export interface ChatResponse {
  'ai_message' : string,
  'is_health_response' : boolean,
}
export type ChatResult = { 'ok' : ChatResponse } |
  { 'tierLimited' : string } |
  { 'error' : string };
export interface CreateOrderResponse {
  'currency' : string,
  'order_id' : string,
  'amount' : bigint,
}
export interface DailyBalanceSummary {
  'date' : string,
  'balance_end' : number,
  'rewards_total' : number,
  'deductions_total' : number,
}
export interface DailyJourney {
  'id' : string,
  'generated_by_ai' : boolean,
  'tasks' : Array<JourneyTask>,
  'date' : Timestamp,
  'total_xp' : bigint,
}
export type DietType = { 'veg' : null } |
  { 'non_veg' : null };
export type DietaryPreference = { 'non_vegetarian' : null } |
  { 'vegetarian' : null };
export interface EditMealPlanRequest { 'meals' : Array<EditableMeal> }
export interface EditMealRequest {
  'task_id' : string,
  'quantity' : string,
  'food_items' : Array<string>,
}
export interface EditableMeal {
  'id' : bigint,
  'calories' : bigint,
  'name' : string,
  'time' : string,
  'quantity' : string,
  'task_type' : JourneyTaskType,
  'food_items' : Array<string>,
  'protein' : bigint,
}
export type EnergyLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type FeedbackResult = { 'ok' : UserFeedback } |
  { 'error' : string } |
  { 'alreadySubmitted' : UserFeedback };
export type GeneratePlanResult = { 'ok' : DailyJourney } |
  { 'tierLimited' : string } |
  { 'error' : string };
export type Goal = { 'muscle_gain' : null } |
  { 'lifestyle_balance' : null } |
  { 'fat_loss' : null };
export interface JourneyCompletionRequest {
  'task_id' : bigint,
  'date' : Timestamp,
}
export interface JourneyProgress {
  'streak_days' : bigint,
  'completed_task_ids' : Array<bigint>,
  'date' : Timestamp,
  'earned_xp' : bigint,
}
export interface JourneyTask {
  'id' : bigint,
  'title' : string,
  'calories' : bigint,
  'name' : string,
  'time' : string,
  'description' : string,
  'xp_reward' : bigint,
  'quantity' : string,
  'task_type' : JourneyTaskType,
  'time_label' : string,
  'food_items' : Array<string>,
  'protein' : bigint,
}
export type JourneyTaskType = { 'meal' : null } |
  { 'water' : null };
export interface LeaderboardEntry {
  'streak_days' : bigint,
  'is_current_user' : boolean,
  'rank' : bigint,
  'weekly_xp' : bigint,
  'display_name' : string,
}
export interface MissedMealEntry { 'meal_type' : string, 'reason' : string }
export interface Payment {
  'status' : PaymentStatus,
  'date' : Timestamp,
  'plan' : [] | [SubscriptionPlan],
  'user_id' : Principal,
  'order_id' : string,
  'payment_id' : string,
  'amount' : bigint,
}
export type PaymentStatus = { 'pending' : null } |
  { 'refunded' : null } |
  { 'success' : null } |
  { 'failed' : null };
export type PlanStatus = { 'trial' : null } |
  { 'premium' : null } |
  { 'free' : null };
export interface RegisterUserRequest {
  'age' : bigint,
  'weight' : [] | [number],
  'height' : [] | [number],
  'lifestyle_description' : [] | [string],
  'dietary_preference' : DietaryPreference,
  'goal' : [] | [Goal],
  'password' : string,
  'name' : string,
  'email' : string,
  'activity_level' : ActivityLevel,
  'diet_type' : [] | [DietType],
}
export interface StreakLeaderboard {
  'current_user_entry' : [] | [LeaderboardEntry],
  'top_entries' : Array<LeaderboardEntry>,
}
export type SubscriptionPlan = { 'premium' : null } |
  { 'free' : null };
export type Timestamp = bigint;
export type TransactionType = { 'reward' : null } |
  { 'deduction' : null } |
  { 'recharge' : null };
export interface UpdateUserRequest {
  'age' : [] | [bigint],
  'weight' : [] | [number],
  'height' : [] | [number],
  'balance' : [] | [number],
  'lifestyle_description' : [] | [string],
  'dietary_preference' : [] | [DietaryPreference],
  'goal' : [] | [Goal],
  'name' : [] | [string],
  'email' : [] | [string],
  'plan_status' : [] | [PlanStatus],
  'activity_level' : [] | [ActivityLevel],
  'diet_type' : [] | [DietType],
}
export interface UserActivity {
  'protein_intake' : [] | [number],
  'daily_calories' : [] | [bigint],
  'date' : Timestamp,
  'water_intake' : [] | [number],
  'user_id' : Principal,
  'total_protein' : [] | [number],
  'meals_skipped' : [] | [bigint],
  'missed_meals' : [] | [Array<MissedMealEntry>],
  'meals_completed' : [] | [bigint],
}
export interface UserFeedback {
  'id' : bigint,
  'energy_level' : EnergyLevel,
  'date' : string,
  'created_at' : bigint,
  'user_id' : Principal,
  'health_status' : string,
  'notes' : string,
  'feedback_text' : string,
}
export interface UserPublic {
  'id' : Principal,
  'age' : bigint,
  'weight' : [] | [number],
  'height' : [] | [number],
  'balance' : number,
  'lifestyle_description' : [] | [string],
  'dietary_preference' : DietaryPreference,
  'goal' : [] | [Goal],
  'name' : string,
  'created_at' : Timestamp,
  'email' : string,
  'plan_status' : PlanStatus,
  'activity_level' : ActivityLevel,
  'subscription_plan' : SubscriptionPlan,
  'diet_type' : DietType,
  'trial_start_date' : [] | [Timestamp],
}
export interface VerifyPaymentRequest {
  'order_id' : string,
  'razorpay_signature' : string,
  'payment_id' : string,
}
export interface WebhookPayload {
  'status' : PaymentStatus,
  'user_id' : Principal,
  'order_id' : string,
  'payment_id' : string,
  'amount' : bigint,
}
export interface WeeklyBalanceReport {
  'total_reward_events' : bigint,
  'total_deduction_events' : bigint,
  'week_net_change' : number,
  'daily_summaries' : Array<DailyBalanceSummary>,
}
export interface _SERVICE {
  'addFeedback' : ActorMethod<[string, AddFeedbackRequest], FeedbackResult>,
  'chatWithAI' : ActorMethod<[string, ChatRequest], ChatResult>,
  'completeJourneyTask' : ActorMethod<
    [string, JourneyCompletionRequest],
    { 'ok' : JourneyProgress } |
      { 'err' : string }
  >,
  'createRazorpayOrder' : ActorMethod<
    [string],
    { 'ok' : CreateOrderResponse } |
      { 'err' : string }
  >,
  'editAIMeal' : ActorMethod<
    [string, EditMealRequest],
    { 'ok' : DailyJourney } |
      { 'err' : string }
  >,
  'editMealPlan' : ActorMethod<
    [string, EditMealPlanRequest],
    { 'ok' : DailyJourney } |
      { 'err' : string }
  >,
  'generateAIDiet' : ActorMethod<[string], GeneratePlanResult>,
  'generateTodayPlan' : ActorMethod<
    [string],
    { 'ok' : DailyJourney } |
      { 'err' : string }
  >,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getFeedbackHistory' : ActorMethod<[string, bigint], Array<UserFeedback>>,
  'getMyActivity' : ActorMethod<
    [string],
    { 'ok' : Array<UserActivity> } |
      { 'err' : string }
  >,
  'getMyBalance' : ActorMethod<
    [string],
    { 'ok' : number } |
      { 'err' : string }
  >,
  'getMyBalanceHistory' : ActorMethod<
    [string],
    { 'ok' : Array<BalanceTransaction> } |
      { 'err' : string }
  >,
  'getMyLatestActivity' : ActorMethod<
    [string],
    { 'ok' : [] | [UserActivity] } |
      { 'err' : string }
  >,
  'getMyPayments' : ActorMethod<
    [string],
    { 'ok' : Array<Payment> } |
      { 'err' : string }
  >,
  'getMyProfile' : ActorMethod<
    [string],
    { 'ok' : UserPublic } |
      { 'err' : string }
  >,
  'getStreakLeaderboard' : ActorMethod<
    [string, bigint],
    { 'ok' : StreakLeaderboard } |
      { 'err' : string }
  >,
  'getTodayFeedback' : ActorMethod<[string], [] | [UserFeedback]>,
  'getTodayJourney' : ActorMethod<
    [string],
    { 'ok' : DailyJourney } |
      { 'err' : string }
  >,
  'getTodayProgress' : ActorMethod<
    [string],
    { 'ok' : JourneyProgress } |
      { 'err' : string }
  >,
  'getWaitlistCount' : ActorMethod<[], bigint>,
  'getWeeklyBalanceReport' : ActorMethod<
    [string],
    { 'ok' : WeeklyBalanceReport } |
      { 'err' : string }
  >,
  'handlePaymentWebhook' : ActorMethod<[WebhookPayload], boolean>,
  'joinWaitlist' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'alreadyExists' : null }
  >,
  'logDailyActivity' : ActorMethod<
    [string, UserActivity],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'logMissedMeal' : ActorMethod<
    [string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'loginUser' : ActorMethod<
    [string, string],
    { 'ok' : AuthResponse } |
      { 'err' : string }
  >,
  'logoutUser' : ActorMethod<[string], undefined>,
  'processDayEndAccountability' : ActorMethod<
    [string, bigint, bigint, boolean, boolean],
    { 'ok' : number } |
      { 'err' : string }
  >,
  'rechargeBalance' : ActorMethod<
    [string, bigint],
    { 'ok' : CreateOrderResponse } |
      { 'err' : string }
  >,
  'registerUser' : ActorMethod<
    [RegisterUserRequest],
    { 'ok' : AuthResponse } |
      { 'err' : string }
  >,
  'resetToAIPlan' : ActorMethod<
    [string],
    { 'ok' : DailyJourney } |
      { 'err' : string }
  >,
  'skipJourneyTask' : ActorMethod<
    [string, bigint, string],
    {
        'ok' : {
          'balance' : number,
          'deducted' : boolean,
          'balance_empty' : boolean,
        }
      } |
      { 'err' : string }
  >,
  'updateMyProfile' : ActorMethod<
    [string, UpdateUserRequest],
    { 'ok' : UserPublic } |
      { 'err' : string }
  >,
  'verifyRazorpayPayment' : ActorMethod<
    [string, VerifyPaymentRequest],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'verifyRechargePayment' : ActorMethod<
    [string, VerifyPaymentRequest, bigint],
    { 'ok' : number } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];