/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RegisterUserRequest {
    age: bigint;
    weight?: number;
    height?: number;
    lifestyle_description?: string;
    dietary_preference: DietaryPreference;
    goal?: Goal;
    password: string;
    name: string;
    email: string;
    activity_level: ActivityLevel;
    diet_type?: DietType;
}
export interface LeaderboardEntry {
    streak_days: bigint;
    is_current_user: boolean;
    rank: bigint;
    weekly_xp: bigint;
    display_name: string;
}
export type Timestamp = bigint;
export interface UserPublic {
    id: Principal;
    age: bigint;
    weight?: number;
    height?: number;
    balance: number;
    lifestyle_description?: string;
    dietary_preference: DietaryPreference;
    goal?: Goal;
    name: string;
    created_at: Timestamp;
    email: string;
    plan_status: PlanStatus;
    activity_level: ActivityLevel;
    subscription_plan: SubscriptionPlan;
    diet_type: DietType;
    trial_start_date?: Timestamp;
}
export type GeneratePlanResult = {
    __kind__: "ok";
    ok: DailyJourney;
} | {
    __kind__: "tierLimited";
    tierLimited: string;
} | {
    __kind__: "error";
    error: string;
};
export interface EditableMeal {
    id: bigint;
    calories: bigint;
    name: string;
    time: string;
    quantity: string;
    task_type: JourneyTaskType;
    food_items: Array<string>;
    protein: bigint;
}
export interface UserActivity {
    protein_intake?: number;
    daily_calories?: bigint;
    date: Timestamp;
    water_intake?: number;
    user_id: Principal;
    total_protein?: number;
    meals_skipped?: bigint;
    missed_meals?: Array<MissedMealEntry>;
    meals_completed?: bigint;
}
export interface CreateOrderResponse {
    currency: string;
    order_id: string;
    amount: bigint;
}
export interface AuthResponse {
    user_id: Principal;
    session_token: string;
}
export interface EditMealPlanRequest {
    meals: Array<EditableMeal>;
}
export interface DailyBalanceSummary {
    date: string;
    balance_end: number;
    rewards_total: number;
    deductions_total: number;
}
export interface ChatRequest {
    user_message: string;
}
export interface MissedMealEntry {
    meal_type: string;
    reason: string;
}
export interface UpdateUserRequest {
    age?: bigint;
    weight?: number;
    height?: number;
    balance?: number;
    lifestyle_description?: string;
    dietary_preference?: DietaryPreference;
    goal?: Goal;
    name?: string;
    email?: string;
    plan_status?: PlanStatus;
    activity_level?: ActivityLevel;
    diet_type?: DietType;
}
export interface WebhookPayload {
    status: PaymentStatus;
    user_id: Principal;
    order_id: string;
    payment_id: string;
    amount: bigint;
}
export interface BalanceTransaction {
    id: string;
    balance_after: number;
    transaction_type: TransactionType;
    date: Timestamp;
    user_id: Principal;
    amount: number;
    reason: string;
}
export interface AddFeedbackRequest {
    energy_level: EnergyLevel;
    date: string;
    health_status: string;
    notes: string;
    feedback_text: string;
}
export interface JourneyCompletionRequest {
    task_id: bigint;
    date: Timestamp;
}
export type ChatResult = {
    __kind__: "ok";
    ok: ChatResponse;
} | {
    __kind__: "tierLimited";
    tierLimited: string;
} | {
    __kind__: "error";
    error: string;
};
export interface JourneyTask {
    id: bigint;
    title: string;
    calories: bigint;
    name: string;
    time: string;
    description: string;
    xp_reward: bigint;
    quantity: string;
    task_type: JourneyTaskType;
    time_label: string;
    food_items: Array<string>;
    protein: bigint;
}
export interface WeeklyBalanceReport {
    total_reward_events: bigint;
    total_deduction_events: bigint;
    week_net_change: number;
    daily_summaries: Array<DailyBalanceSummary>;
}
export interface Payment {
    status: PaymentStatus;
    date: Timestamp;
    plan?: SubscriptionPlan;
    user_id: Principal;
    order_id: string;
    payment_id: string;
    amount: bigint;
}
export type FeedbackResult = {
    __kind__: "ok";
    ok: UserFeedback;
} | {
    __kind__: "error";
    error: string;
} | {
    __kind__: "alreadySubmitted";
    alreadySubmitted: UserFeedback;
};
export interface EditMealRequest {
    task_id: string;
    quantity: string;
    food_items: Array<string>;
}
export interface StreakLeaderboard {
    current_user_entry?: LeaderboardEntry;
    top_entries: Array<LeaderboardEntry>;
}
export interface DailyJourney {
    id: string;
    generated_by_ai: boolean;
    tasks: Array<JourneyTask>;
    date: Timestamp;
    total_xp: bigint;
}
export interface ChatResponse {
    ai_message: string;
    is_health_response: boolean;
}
export interface AdminStats {
    total_users: bigint;
    premium_users: bigint;
    active_users: bigint;
    total_waitlist: bigint;
}
export interface VerifyPaymentRequest {
    order_id: string;
    razorpay_signature: string;
    payment_id: string;
}
export interface UserFeedback {
    id: bigint;
    energy_level: EnergyLevel;
    date: string;
    created_at: bigint;
    user_id: Principal;
    health_status: string;
    notes: string;
    feedback_text: string;
}
export interface JourneyProgress {
    streak_days: bigint;
    completed_task_ids: Array<bigint>;
    date: Timestamp;
    earned_xp: bigint;
}
export enum ActivityLevel {
    intense = "intense",
    light = "light",
    sedentary = "sedentary",
    moderate = "moderate"
}
export enum DietType {
    veg = "veg",
    non_veg = "non_veg"
}
export enum DietaryPreference {
    non_vegetarian = "non_vegetarian",
    vegetarian = "vegetarian"
}
export enum EnergyLevel {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum Goal {
    muscle_gain = "muscle_gain",
    lifestyle_balance = "lifestyle_balance",
    fat_loss = "fat_loss"
}
export enum JourneyTaskType {
    meal = "meal",
    water = "water"
}
export enum PaymentStatus {
    pending = "pending",
    refunded = "refunded",
    success = "success",
    failed = "failed"
}
export enum PlanStatus {
    trial = "trial",
    premium = "premium",
    free = "free"
}
export enum SubscriptionPlan {
    premium = "premium",
    free = "free"
}
export enum TransactionType {
    reward = "reward",
    deduction = "deduction",
    recharge = "recharge"
}
export enum Variant_ok_alreadyExists {
    ok = "ok",
    alreadyExists = "alreadyExists"
}
export interface backendInterface {
    addFeedback(sessionToken: string, req: AddFeedbackRequest): Promise<FeedbackResult>;
    chatWithAI(sessionToken: string, req: ChatRequest): Promise<ChatResult>;
    completeJourneyTask(sessionToken: string, req: JourneyCompletionRequest): Promise<{
        __kind__: "ok";
        ok: JourneyProgress;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createRazorpayOrder(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: CreateOrderResponse;
    } | {
        __kind__: "err";
        err: string;
    }>;
    editAIMeal(sessionToken: string, req: EditMealRequest): Promise<{
        __kind__: "ok";
        ok: DailyJourney;
    } | {
        __kind__: "err";
        err: string;
    }>;
    editMealPlan(sessionToken: string, req: EditMealPlanRequest): Promise<{
        __kind__: "ok";
        ok: DailyJourney;
    } | {
        __kind__: "err";
        err: string;
    }>;
    generateAIDiet(sessionToken: string): Promise<GeneratePlanResult>;
    generateTodayPlan(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: DailyJourney;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getAdminStats(): Promise<AdminStats>;
    getFeedbackHistory(sessionToken: string, days: bigint): Promise<Array<UserFeedback>>;
    getMyActivity(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: Array<UserActivity>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getMyBalance(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: number;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getMyBalanceHistory(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: Array<BalanceTransaction>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getMyLatestActivity(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: UserActivity | null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getMyPayments(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: Array<Payment>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getMyProfile(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: UserPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getStreakLeaderboard(sessionToken: string, limit: bigint): Promise<{
        __kind__: "ok";
        ok: StreakLeaderboard;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getTodayFeedback(sessionToken: string): Promise<UserFeedback | null>;
    getTodayJourney(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: DailyJourney;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getTodayProgress(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: JourneyProgress;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getWaitlistCount(): Promise<bigint>;
    getWeeklyBalanceReport(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: WeeklyBalanceReport;
    } | {
        __kind__: "err";
        err: string;
    }>;
    handlePaymentWebhook(payload: WebhookPayload): Promise<boolean>;
    joinWaitlist(email: string): Promise<Variant_ok_alreadyExists>;
    logDailyActivity(sessionToken: string, entry: UserActivity): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    logMissedMeal(sessionToken: string, mealType: string, reason: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    loginUser(email: string, password: string): Promise<{
        __kind__: "ok";
        ok: AuthResponse;
    } | {
        __kind__: "err";
        err: string;
    }>;
    logoutUser(sessionToken: string): Promise<void>;
    processDayEndAccountability(sessionToken: string, mealsCompleted: bigint, mealsSkipped: bigint, waterCompleted: boolean, skippedWithReason: boolean): Promise<{
        __kind__: "ok";
        ok: number;
    } | {
        __kind__: "err";
        err: string;
    }>;
    rechargeBalance(sessionToken: string, amountPaise: bigint): Promise<{
        __kind__: "ok";
        ok: CreateOrderResponse;
    } | {
        __kind__: "err";
        err: string;
    }>;
    registerUser(req: RegisterUserRequest): Promise<{
        __kind__: "ok";
        ok: AuthResponse;
    } | {
        __kind__: "err";
        err: string;
    }>;
    resetToAIPlan(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: DailyJourney;
    } | {
        __kind__: "err";
        err: string;
    }>;
    skipJourneyTask(sessionToken: string, taskId: bigint, reason: string): Promise<{
        __kind__: "ok";
        ok: {
            balance: number;
            deducted: boolean;
            balance_empty: boolean;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateMyProfile(sessionToken: string, req: UpdateUserRequest): Promise<{
        __kind__: "ok";
        ok: UserPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    verifyRazorpayPayment(sessionToken: string, req: VerifyPaymentRequest): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    verifyRechargePayment(sessionToken: string, req: VerifyPaymentRequest, amountPaise: bigint): Promise<{
        __kind__: "ok";
        ok: number;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { ActivityLevel as _ActivityLevel, AddFeedbackRequest as _AddFeedbackRequest, AuthResponse as _AuthResponse, BalanceTransaction as _BalanceTransaction, ChatResponse as _ChatResponse, ChatResult as _ChatResult, CreateOrderResponse as _CreateOrderResponse, DailyJourney as _DailyJourney, DietType as _DietType, DietaryPreference as _DietaryPreference, EditMealPlanRequest as _EditMealPlanRequest, EditableMeal as _EditableMeal, EnergyLevel as _EnergyLevel, FeedbackResult as _FeedbackResult, GeneratePlanResult as _GeneratePlanResult, Goal as _Goal, JourneyProgress as _JourneyProgress, JourneyTask as _JourneyTask, JourneyTaskType as _JourneyTaskType, LeaderboardEntry as _LeaderboardEntry, MissedMealEntry as _MissedMealEntry, Payment as _Payment, PaymentStatus as _PaymentStatus, PlanStatus as _PlanStatus, RegisterUserRequest as _RegisterUserRequest, StreakLeaderboard as _StreakLeaderboard, SubscriptionPlan as _SubscriptionPlan, Timestamp as _Timestamp, TransactionType as _TransactionType, UpdateUserRequest as _UpdateUserRequest, UserActivity as _UserActivity, UserFeedback as _UserFeedback, UserPublic as _UserPublic, WebhookPayload as _WebhookPayload, WeeklyBalanceReport as _WeeklyBalanceReport } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFeedback(arg0: string, arg1: AddFeedbackRequest): Promise<FeedbackResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addFeedback(arg0, to_candid_AddFeedbackRequest_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_FeedbackResult_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFeedback(arg0, to_candid_AddFeedbackRequest_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_FeedbackResult_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async chatWithAI(arg0: string, arg1: ChatRequest): Promise<ChatResult> {
        if (this.processError) {
            try {
                const result = await this.actor.chatWithAI(arg0, arg1);
                return from_candid_ChatResult_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.chatWithAI(arg0, arg1);
            return from_candid_ChatResult_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async completeJourneyTask(arg0: string, arg1: JourneyCompletionRequest): Promise<{
        __kind__: "ok";
        ok: JourneyProgress;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.completeJourneyTask(arg0, arg1);
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeJourneyTask(arg0, arg1);
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRazorpayOrder(arg0: string): Promise<{
        __kind__: "ok";
        ok: CreateOrderResponse;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createRazorpayOrder(arg0);
                return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRazorpayOrder(arg0);
            return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async editAIMeal(arg0: string, arg1: EditMealRequest): Promise<{
        __kind__: "ok";
        ok: DailyJourney;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.editAIMeal(arg0, arg1);
                return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editAIMeal(arg0, arg1);
            return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async editMealPlan(arg0: string, arg1: EditMealPlanRequest): Promise<{
        __kind__: "ok";
        ok: DailyJourney;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.editMealPlan(arg0, to_candid_EditMealPlanRequest_n23(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editMealPlan(arg0, to_candid_EditMealPlanRequest_n23(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateAIDiet(arg0: string): Promise<GeneratePlanResult> {
        if (this.processError) {
            try {
                const result = await this.actor.generateAIDiet(arg0);
                return from_candid_GeneratePlanResult_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateAIDiet(arg0);
            return from_candid_GeneratePlanResult_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateTodayPlan(arg0: string): Promise<{
        __kind__: "ok";
        ok: DailyJourney;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.generateTodayPlan(arg0);
                return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateTodayPlan(arg0);
            return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getFeedbackHistory(arg0: string, arg1: bigint): Promise<Array<UserFeedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedbackHistory(arg0, arg1);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedbackHistory(arg0, arg1);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyActivity(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<UserActivity>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyActivity(arg0);
                return from_candid_variant_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyActivity(arg0);
            return from_candid_variant_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBalance(arg0: string): Promise<{
        __kind__: "ok";
        ok: number;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBalance(arg0);
                return from_candid_variant_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBalance(arg0);
            return from_candid_variant_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBalanceHistory(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<BalanceTransaction>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBalanceHistory(arg0);
                return from_candid_variant_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBalanceHistory(arg0);
            return from_candid_variant_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyLatestActivity(arg0: string): Promise<{
        __kind__: "ok";
        ok: UserActivity | null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLatestActivity(arg0);
                return from_candid_variant_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLatestActivity(arg0);
            return from_candid_variant_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPayments(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<Payment>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPayments(arg0);
                return from_candid_variant_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPayments(arg0);
            return from_candid_variant_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(arg0: string): Promise<{
        __kind__: "ok";
        ok: UserPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile(arg0);
                return from_candid_variant_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile(arg0);
            return from_candid_variant_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStreakLeaderboard(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: StreakLeaderboard;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getStreakLeaderboard(arg0, arg1);
                return from_candid_variant_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStreakLeaderboard(arg0, arg1);
            return from_candid_variant_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodayFeedback(arg0: string): Promise<UserFeedback | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodayFeedback(arg0);
                return from_candid_opt_n78(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodayFeedback(arg0);
            return from_candid_opt_n78(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodayJourney(arg0: string): Promise<{
        __kind__: "ok";
        ok: DailyJourney;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodayJourney(arg0);
                return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodayJourney(arg0);
            return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodayProgress(arg0: string): Promise<{
        __kind__: "ok";
        ok: JourneyProgress;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodayProgress(arg0);
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodayProgress(arg0);
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWaitlistCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getWaitlistCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWaitlistCount();
            return result;
        }
    }
    async getWeeklyBalanceReport(arg0: string): Promise<{
        __kind__: "ok";
        ok: WeeklyBalanceReport;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyBalanceReport(arg0);
                return from_candid_variant_n79(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyBalanceReport(arg0);
            return from_candid_variant_n79(this._uploadFile, this._downloadFile, result);
        }
    }
    async handlePaymentWebhook(arg0: WebhookPayload): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.handlePaymentWebhook(to_candid_WebhookPayload_n80(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.handlePaymentWebhook(to_candid_WebhookPayload_n80(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async joinWaitlist(arg0: string): Promise<Variant_ok_alreadyExists> {
        if (this.processError) {
            try {
                const result = await this.actor.joinWaitlist(arg0);
                return from_candid_variant_n84(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinWaitlist(arg0);
            return from_candid_variant_n84(this._uploadFile, this._downloadFile, result);
        }
    }
    async logDailyActivity(arg0: string, arg1: UserActivity): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.logDailyActivity(arg0, to_candid_UserActivity_n85(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n87(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logDailyActivity(arg0, to_candid_UserActivity_n85(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n87(this._uploadFile, this._downloadFile, result);
        }
    }
    async logMissedMeal(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.logMissedMeal(arg0, arg1, arg2);
                return from_candid_variant_n88(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logMissedMeal(arg0, arg1, arg2);
            return from_candid_variant_n88(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginUser(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: AuthResponse;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUser(arg0, arg1);
                return from_candid_variant_n89(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUser(arg0, arg1);
            return from_candid_variant_n89(this._uploadFile, this._downloadFile, result);
        }
    }
    async logoutUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logoutUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logoutUser(arg0);
            return result;
        }
    }
    async processDayEndAccountability(arg0: string, arg1: bigint, arg2: bigint, arg3: boolean, arg4: boolean): Promise<{
        __kind__: "ok";
        ok: number;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.processDayEndAccountability(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processDayEndAccountability(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async rechargeBalance(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: CreateOrderResponse;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.rechargeBalance(arg0, arg1);
                return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rechargeBalance(arg0, arg1);
            return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: RegisterUserRequest): Promise<{
        __kind__: "ok";
        ok: AuthResponse;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(to_candid_RegisterUserRequest_n90(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n89(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(to_candid_RegisterUserRequest_n90(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n89(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetToAIPlan(arg0: string): Promise<{
        __kind__: "ok";
        ok: DailyJourney;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.resetToAIPlan(arg0);
                return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetToAIPlan(arg0);
            return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async skipJourneyTask(arg0: string, arg1: bigint, arg2: string): Promise<{
        __kind__: "ok";
        ok: {
            balance: number;
            deducted: boolean;
            balance_empty: boolean;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.skipJourneyTask(arg0, arg1, arg2);
                return from_candid_variant_n100(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.skipJourneyTask(arg0, arg1, arg2);
            return from_candid_variant_n100(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMyProfile(arg0: string, arg1: UpdateUserRequest): Promise<{
        __kind__: "ok";
        ok: UserPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(arg0, to_candid_UpdateUserRequest_n101(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(arg0, to_candid_UpdateUserRequest_n101(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyRazorpayPayment(arg0: string, arg1: VerifyPaymentRequest): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyRazorpayPayment(arg0, arg1);
                return from_candid_variant_n105(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyRazorpayPayment(arg0, arg1);
            return from_candid_variant_n105(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyRechargePayment(arg0: string, arg1: VerifyPaymentRequest, arg2: bigint): Promise<{
        __kind__: "ok";
        ok: number;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyRechargePayment(arg0, arg1, arg2);
                return from_candid_variant_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyRechargePayment(arg0, arg1, arg2);
            return from_candid_variant_n40(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ActivityLevel_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityLevel): ActivityLevel {
    return from_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function from_candid_BalanceTransaction_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BalanceTransaction): BalanceTransaction {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_ChatResult_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatResult): ChatResult {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_DailyJourney_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyJourney): DailyJourney {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_DietType_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DietType): DietType {
    return from_candid_variant_n72(_uploadFile, _downloadFile, value);
}
function from_candid_DietaryPreference_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DietaryPreference): DietaryPreference {
    return from_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function from_candid_EnergyLevel_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EnergyLevel): EnergyLevel {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_FeedbackResult_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedbackResult): FeedbackResult {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_GeneratePlanResult_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GeneratePlanResult): GeneratePlanResult {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Goal_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Goal): Goal {
    return from_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function from_candid_JourneyTaskType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JourneyTaskType): JourneyTaskType {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_JourneyTask_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JourneyTask): JourneyTask {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_PlanStatus_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlanStatus): PlanStatus {
    return from_candid_variant_n68(_uploadFile, _downloadFile, value);
}
function from_candid_StreakLeaderboard_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StreakLeaderboard): StreakLeaderboard {
    return from_candid_record_n76(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionPlan_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionPlan): SubscriptionPlan {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_UserActivity_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserActivity): UserActivity {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserFeedback_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserFeedback): UserFeedback {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserPublic_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPublic): UserPublic {
    return from_candid_record_n60(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_MissedMealEntry>]): Array<MissedMealEntry> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserActivity]): UserActivity | null {
    return value.length === 0 ? null : from_candid_UserActivity_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubscriptionPlan]): SubscriptionPlan | null {
    return value.length === 0 ? null : from_candid_SubscriptionPlan_n56(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Goal]): Goal | null {
    return value.length === 0 ? null : from_candid_Goal_n65(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LeaderboardEntry]): LeaderboardEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserFeedback]): UserFeedback | null {
    return value.length === 0 ? null : from_candid_UserFeedback_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    generated_by_ai: boolean;
    tasks: Array<_JourneyTask>;
    date: _Timestamp;
    total_xp: bigint;
}): {
    id: string;
    generated_by_ai: boolean;
    tasks: Array<JourneyTask>;
    date: Timestamp;
    total_xp: bigint;
} {
    return {
        id: value.id,
        generated_by_ai: value.generated_by_ai,
        tasks: from_candid_vec_n18(_uploadFile, _downloadFile, value.tasks),
        date: value.date,
        total_xp: value.total_xp
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    calories: bigint;
    name: string;
    time: string;
    description: string;
    xp_reward: bigint;
    quantity: string;
    task_type: _JourneyTaskType;
    time_label: string;
    food_items: Array<string>;
    protein: bigint;
}): {
    id: bigint;
    title: string;
    calories: bigint;
    name: string;
    time: string;
    description: string;
    xp_reward: bigint;
    quantity: string;
    task_type: JourneyTaskType;
    time_label: string;
    food_items: Array<string>;
    protein: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        calories: value.calories,
        name: value.name,
        time: value.time,
        description: value.description,
        xp_reward: value.xp_reward,
        quantity: value.quantity,
        task_type: from_candid_JourneyTaskType_n21(_uploadFile, _downloadFile, value.task_type),
        time_label: value.time_label,
        food_items: value.food_items,
        protein: value.protein
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    protein_intake: [] | [number];
    daily_calories: [] | [bigint];
    date: _Timestamp;
    water_intake: [] | [number];
    user_id: Principal;
    total_protein: [] | [number];
    meals_skipped: [] | [bigint];
    missed_meals: [] | [Array<_MissedMealEntry>];
    meals_completed: [] | [bigint];
}): {
    protein_intake?: number;
    daily_calories?: bigint;
    date: Timestamp;
    water_intake?: number;
    user_id: Principal;
    total_protein?: number;
    meals_skipped?: bigint;
    missed_meals?: Array<MissedMealEntry>;
    meals_completed?: bigint;
} {
    return {
        protein_intake: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.protein_intake)),
        daily_calories: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.daily_calories)),
        date: value.date,
        water_intake: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.water_intake)),
        user_id: value.user_id,
        total_protein: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.total_protein)),
        meals_skipped: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.meals_skipped)),
        missed_meals: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.missed_meals)),
        meals_completed: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.meals_completed))
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    balance_after: number;
    transaction_type: _TransactionType;
    date: _Timestamp;
    user_id: Principal;
    amount: number;
    reason: string;
}): {
    id: string;
    balance_after: number;
    transaction_type: TransactionType;
    date: Timestamp;
    user_id: Principal;
    amount: number;
    reason: string;
} {
    return {
        id: value.id,
        balance_after: value.balance_after,
        transaction_type: from_candid_TransactionType_n45(_uploadFile, _downloadFile, value.transaction_type),
        date: value.date,
        user_id: value.user_id,
        amount: value.amount,
        reason: value.reason
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PaymentStatus;
    date: _Timestamp;
    plan: [] | [_SubscriptionPlan];
    user_id: Principal;
    order_id: string;
    payment_id: string;
    amount: bigint;
}): {
    status: PaymentStatus;
    date: Timestamp;
    plan?: SubscriptionPlan;
    user_id: Principal;
    order_id: string;
    payment_id: string;
    amount: bigint;
} {
    return {
        status: from_candid_PaymentStatus_n53(_uploadFile, _downloadFile, value.status),
        date: value.date,
        plan: record_opt_to_undefined(from_candid_opt_n55(_uploadFile, _downloadFile, value.plan)),
        user_id: value.user_id,
        order_id: value.order_id,
        payment_id: value.payment_id,
        amount: value.amount
    };
}
function from_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    age: bigint;
    weight: [] | [number];
    height: [] | [number];
    balance: number;
    lifestyle_description: [] | [string];
    dietary_preference: _DietaryPreference;
    goal: [] | [_Goal];
    name: string;
    created_at: _Timestamp;
    email: string;
    plan_status: _PlanStatus;
    activity_level: _ActivityLevel;
    subscription_plan: _SubscriptionPlan;
    diet_type: _DietType;
    trial_start_date: [] | [_Timestamp];
}): {
    id: Principal;
    age: bigint;
    weight?: number;
    height?: number;
    balance: number;
    lifestyle_description?: string;
    dietary_preference: DietaryPreference;
    goal?: Goal;
    name: string;
    created_at: Timestamp;
    email: string;
    plan_status: PlanStatus;
    activity_level: ActivityLevel;
    subscription_plan: SubscriptionPlan;
    diet_type: DietType;
    trial_start_date?: Timestamp;
} {
    return {
        id: value.id,
        age: value.age,
        weight: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.weight)),
        height: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.height)),
        balance: value.balance,
        lifestyle_description: record_opt_to_undefined(from_candid_opt_n61(_uploadFile, _downloadFile, value.lifestyle_description)),
        dietary_preference: from_candid_DietaryPreference_n62(_uploadFile, _downloadFile, value.dietary_preference),
        goal: record_opt_to_undefined(from_candid_opt_n64(_uploadFile, _downloadFile, value.goal)),
        name: value.name,
        created_at: value.created_at,
        email: value.email,
        plan_status: from_candid_PlanStatus_n67(_uploadFile, _downloadFile, value.plan_status),
        activity_level: from_candid_ActivityLevel_n69(_uploadFile, _downloadFile, value.activity_level),
        subscription_plan: from_candid_SubscriptionPlan_n56(_uploadFile, _downloadFile, value.subscription_plan),
        diet_type: from_candid_DietType_n71(_uploadFile, _downloadFile, value.diet_type),
        trial_start_date: record_opt_to_undefined(from_candid_opt_n73(_uploadFile, _downloadFile, value.trial_start_date))
    };
}
function from_candid_record_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    current_user_entry: [] | [_LeaderboardEntry];
    top_entries: Array<_LeaderboardEntry>;
}): {
    current_user_entry?: LeaderboardEntry;
    top_entries: Array<LeaderboardEntry>;
} {
    return {
        current_user_entry: record_opt_to_undefined(from_candid_opt_n77(_uploadFile, _downloadFile, value.current_user_entry)),
        top_entries: value.top_entries
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    energy_level: _EnergyLevel;
    date: string;
    created_at: bigint;
    user_id: Principal;
    health_status: string;
    notes: string;
    feedback_text: string;
}): {
    id: bigint;
    energy_level: EnergyLevel;
    date: string;
    created_at: bigint;
    user_id: Principal;
    health_status: string;
    notes: string;
    feedback_text: string;
} {
    return {
        id: value.id,
        energy_level: from_candid_EnergyLevel_n9(_uploadFile, _downloadFile, value.energy_level),
        date: value.date,
        created_at: value.created_at,
        user_id: value.user_id,
        health_status: value.health_status,
        notes: value.notes,
        feedback_text: value.feedback_text
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): EnergyLevel {
    return "low" in value ? EnergyLevel.low : "high" in value ? EnergyLevel.high : "medium" in value ? EnergyLevel.medium : value;
}
function from_candid_variant_n100(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        balance: number;
        deducted: boolean;
        balance_empty: boolean;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        balance: number;
        deducted: boolean;
        balance_empty: boolean;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n105(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ChatResponse;
} | {
    tierLimited: string;
} | {
    error: string;
}): {
    __kind__: "ok";
    ok: ChatResponse;
} | {
    __kind__: "tierLimited";
    tierLimited: string;
} | {
    __kind__: "error";
    error: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "tierLimited" in value ? {
        __kind__: "tierLimited",
        tierLimited: value.tierLimited
    } : "error" in value ? {
        __kind__: "error",
        error: value.error
    } : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _JourneyProgress;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: JourneyProgress;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CreateOrderResponse;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CreateOrderResponse;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _DailyJourney;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: DailyJourney;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_DailyJourney_n16(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    meal: null;
} | {
    water: null;
}): JourneyTaskType {
    return "meal" in value ? JourneyTaskType.meal : "water" in value ? JourneyTaskType.water : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _DailyJourney;
} | {
    tierLimited: string;
} | {
    error: string;
}): {
    __kind__: "ok";
    ok: DailyJourney;
} | {
    __kind__: "tierLimited";
    tierLimited: string;
} | {
    __kind__: "error";
    error: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_DailyJourney_n16(_uploadFile, _downloadFile, value.ok)
    } : "tierLimited" in value ? {
        __kind__: "tierLimited",
        tierLimited: value.tierLimited
    } : "error" in value ? {
        __kind__: "error",
        error: value.error
    } : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_UserActivity>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<UserActivity>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n34(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: number;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: number;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_BalanceTransaction>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<BalanceTransaction>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n42(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reward: null;
} | {
    deduction: null;
} | {
    recharge: null;
}): TransactionType {
    return "reward" in value ? TransactionType.reward : "deduction" in value ? TransactionType.deduction : "recharge" in value ? TransactionType.recharge : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: [] | [_UserActivity];
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserActivity | null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_opt_n48(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Payment>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<Payment>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n50(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    refunded: null;
} | {
    success: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "refunded" in value ? PaymentStatus.refunded : "success" in value ? PaymentStatus.success : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premium: null;
} | {
    free: null;
}): SubscriptionPlan {
    return "premium" in value ? SubscriptionPlan.premium : "free" in value ? SubscriptionPlan.free : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserPublic_n59(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserFeedback;
} | {
    error: string;
} | {
    alreadySubmitted: _UserFeedback;
}): {
    __kind__: "ok";
    ok: UserFeedback;
} | {
    __kind__: "error";
    error: string;
} | {
    __kind__: "alreadySubmitted";
    alreadySubmitted: UserFeedback;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserFeedback_n7(_uploadFile, _downloadFile, value.ok)
    } : "error" in value ? {
        __kind__: "error",
        error: value.error
    } : "alreadySubmitted" in value ? {
        __kind__: "alreadySubmitted",
        alreadySubmitted: from_candid_UserFeedback_n7(_uploadFile, _downloadFile, value.alreadySubmitted)
    } : value;
}
function from_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    non_vegetarian: null;
} | {
    vegetarian: null;
}): DietaryPreference {
    return "non_vegetarian" in value ? DietaryPreference.non_vegetarian : "vegetarian" in value ? DietaryPreference.vegetarian : value;
}
function from_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    muscle_gain: null;
} | {
    lifestyle_balance: null;
} | {
    fat_loss: null;
}): Goal {
    return "muscle_gain" in value ? Goal.muscle_gain : "lifestyle_balance" in value ? Goal.lifestyle_balance : "fat_loss" in value ? Goal.fat_loss : value;
}
function from_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trial: null;
} | {
    premium: null;
} | {
    free: null;
}): PlanStatus {
    return "trial" in value ? PlanStatus.trial : "premium" in value ? PlanStatus.premium : "free" in value ? PlanStatus.free : value;
}
function from_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intense: null;
} | {
    light: null;
} | {
    sedentary: null;
} | {
    moderate: null;
}): ActivityLevel {
    return "intense" in value ? ActivityLevel.intense : "light" in value ? ActivityLevel.light : "sedentary" in value ? ActivityLevel.sedentary : "moderate" in value ? ActivityLevel.moderate : value;
}
function from_candid_variant_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    veg: null;
} | {
    non_veg: null;
}): DietType {
    return "veg" in value ? DietType.veg : "non_veg" in value ? DietType.non_veg : value;
}
function from_candid_variant_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _StreakLeaderboard;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: StreakLeaderboard;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_StreakLeaderboard_n75(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _WeeklyBalanceReport;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: WeeklyBalanceReport;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    alreadyExists: null;
}): Variant_ok_alreadyExists {
    return "ok" in value ? Variant_ok_alreadyExists.ok : "alreadyExists" in value ? Variant_ok_alreadyExists.alreadyExists : value;
}
function from_candid_variant_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AuthResponse;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AuthResponse;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JourneyTask>): Array<JourneyTask> {
    return value.map((x)=>from_candid_JourneyTask_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserFeedback>): Array<UserFeedback> {
    return value.map((x)=>from_candid_UserFeedback_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserActivity>): Array<UserActivity> {
    return value.map((x)=>from_candid_UserActivity_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BalanceTransaction>): Array<BalanceTransaction> {
    return value.map((x)=>from_candid_BalanceTransaction_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n51(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityLevel_n96(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityLevel): _ActivityLevel {
    return to_candid_variant_n97(_uploadFile, _downloadFile, value);
}
function to_candid_AddFeedbackRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddFeedbackRequest): _AddFeedbackRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_DietType_n98(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietType): _DietType {
    return to_candid_variant_n99(_uploadFile, _downloadFile, value);
}
function to_candid_DietaryPreference_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietaryPreference): _DietaryPreference {
    return to_candid_variant_n93(_uploadFile, _downloadFile, value);
}
function to_candid_EditMealPlanRequest_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EditMealPlanRequest): _EditMealPlanRequest {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_EditableMeal_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EditableMeal): _EditableMeal {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_EnergyLevel_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnergyLevel): _EnergyLevel {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Goal_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Goal): _Goal {
    return to_candid_variant_n95(_uploadFile, _downloadFile, value);
}
function to_candid_JourneyTaskType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JourneyTaskType): _JourneyTaskType {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n83(_uploadFile, _downloadFile, value);
}
function to_candid_PlanStatus_n103(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanStatus): _PlanStatus {
    return to_candid_variant_n104(_uploadFile, _downloadFile, value);
}
function to_candid_RegisterUserRequest_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegisterUserRequest): _RegisterUserRequest {
    return to_candid_record_n91(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateUserRequest_n101(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateUserRequest): _UpdateUserRequest {
    return to_candid_record_n102(_uploadFile, _downloadFile, value);
}
function to_candid_UserActivity_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserActivity): _UserActivity {
    return to_candid_record_n86(_uploadFile, _downloadFile, value);
}
function to_candid_WebhookPayload_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WebhookPayload): _WebhookPayload {
    return to_candid_record_n81(_uploadFile, _downloadFile, value);
}
function to_candid_record_n102(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age?: bigint;
    weight?: number;
    height?: number;
    balance?: number;
    lifestyle_description?: string;
    dietary_preference?: DietaryPreference;
    goal?: Goal;
    name?: string;
    email?: string;
    plan_status?: PlanStatus;
    activity_level?: ActivityLevel;
    diet_type?: DietType;
}): {
    age: [] | [bigint];
    weight: [] | [number];
    height: [] | [number];
    balance: [] | [number];
    lifestyle_description: [] | [string];
    dietary_preference: [] | [_DietaryPreference];
    goal: [] | [_Goal];
    name: [] | [string];
    email: [] | [string];
    plan_status: [] | [_PlanStatus];
    activity_level: [] | [_ActivityLevel];
    diet_type: [] | [_DietType];
} {
    return {
        age: value.age ? candid_some(value.age) : candid_none(),
        weight: value.weight ? candid_some(value.weight) : candid_none(),
        height: value.height ? candid_some(value.height) : candid_none(),
        balance: value.balance ? candid_some(value.balance) : candid_none(),
        lifestyle_description: value.lifestyle_description ? candid_some(value.lifestyle_description) : candid_none(),
        dietary_preference: value.dietary_preference ? candid_some(to_candid_DietaryPreference_n92(_uploadFile, _downloadFile, value.dietary_preference)) : candid_none(),
        goal: value.goal ? candid_some(to_candid_Goal_n94(_uploadFile, _downloadFile, value.goal)) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none(),
        plan_status: value.plan_status ? candid_some(to_candid_PlanStatus_n103(_uploadFile, _downloadFile, value.plan_status)) : candid_none(),
        activity_level: value.activity_level ? candid_some(to_candid_ActivityLevel_n96(_uploadFile, _downloadFile, value.activity_level)) : candid_none(),
        diet_type: value.diet_type ? candid_some(to_candid_DietType_n98(_uploadFile, _downloadFile, value.diet_type)) : candid_none()
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    energy_level: EnergyLevel;
    date: string;
    health_status: string;
    notes: string;
    feedback_text: string;
}): {
    energy_level: _EnergyLevel;
    date: string;
    health_status: string;
    notes: string;
    feedback_text: string;
} {
    return {
        energy_level: to_candid_EnergyLevel_n3(_uploadFile, _downloadFile, value.energy_level),
        date: value.date,
        health_status: value.health_status,
        notes: value.notes,
        feedback_text: value.feedback_text
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    meals: Array<EditableMeal>;
}): {
    meals: Array<_EditableMeal>;
} {
    return {
        meals: to_candid_vec_n25(_uploadFile, _downloadFile, value.meals)
    };
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    calories: bigint;
    name: string;
    time: string;
    quantity: string;
    task_type: JourneyTaskType;
    food_items: Array<string>;
    protein: bigint;
}): {
    id: bigint;
    calories: bigint;
    name: string;
    time: string;
    quantity: string;
    task_type: _JourneyTaskType;
    food_items: Array<string>;
    protein: bigint;
} {
    return {
        id: value.id,
        calories: value.calories,
        name: value.name,
        time: value.time,
        quantity: value.quantity,
        task_type: to_candid_JourneyTaskType_n28(_uploadFile, _downloadFile, value.task_type),
        food_items: value.food_items,
        protein: value.protein
    };
}
function to_candid_record_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: PaymentStatus;
    user_id: Principal;
    order_id: string;
    payment_id: string;
    amount: bigint;
}): {
    status: _PaymentStatus;
    user_id: Principal;
    order_id: string;
    payment_id: string;
    amount: bigint;
} {
    return {
        status: to_candid_PaymentStatus_n82(_uploadFile, _downloadFile, value.status),
        user_id: value.user_id,
        order_id: value.order_id,
        payment_id: value.payment_id,
        amount: value.amount
    };
}
function to_candid_record_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    protein_intake?: number;
    daily_calories?: bigint;
    date: Timestamp;
    water_intake?: number;
    user_id: Principal;
    total_protein?: number;
    meals_skipped?: bigint;
    missed_meals?: Array<MissedMealEntry>;
    meals_completed?: bigint;
}): {
    protein_intake: [] | [number];
    daily_calories: [] | [bigint];
    date: _Timestamp;
    water_intake: [] | [number];
    user_id: Principal;
    total_protein: [] | [number];
    meals_skipped: [] | [bigint];
    missed_meals: [] | [Array<_MissedMealEntry>];
    meals_completed: [] | [bigint];
} {
    return {
        protein_intake: value.protein_intake ? candid_some(value.protein_intake) : candid_none(),
        daily_calories: value.daily_calories ? candid_some(value.daily_calories) : candid_none(),
        date: value.date,
        water_intake: value.water_intake ? candid_some(value.water_intake) : candid_none(),
        user_id: value.user_id,
        total_protein: value.total_protein ? candid_some(value.total_protein) : candid_none(),
        meals_skipped: value.meals_skipped ? candid_some(value.meals_skipped) : candid_none(),
        missed_meals: value.missed_meals ? candid_some(value.missed_meals) : candid_none(),
        meals_completed: value.meals_completed ? candid_some(value.meals_completed) : candid_none()
    };
}
function to_candid_record_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    weight?: number;
    height?: number;
    lifestyle_description?: string;
    dietary_preference: DietaryPreference;
    goal?: Goal;
    password: string;
    name: string;
    email: string;
    activity_level: ActivityLevel;
    diet_type?: DietType;
}): {
    age: bigint;
    weight: [] | [number];
    height: [] | [number];
    lifestyle_description: [] | [string];
    dietary_preference: _DietaryPreference;
    goal: [] | [_Goal];
    password: string;
    name: string;
    email: string;
    activity_level: _ActivityLevel;
    diet_type: [] | [_DietType];
} {
    return {
        age: value.age,
        weight: value.weight ? candid_some(value.weight) : candid_none(),
        height: value.height ? candid_some(value.height) : candid_none(),
        lifestyle_description: value.lifestyle_description ? candid_some(value.lifestyle_description) : candid_none(),
        dietary_preference: to_candid_DietaryPreference_n92(_uploadFile, _downloadFile, value.dietary_preference),
        goal: value.goal ? candid_some(to_candid_Goal_n94(_uploadFile, _downloadFile, value.goal)) : candid_none(),
        password: value.password,
        name: value.name,
        email: value.email,
        activity_level: to_candid_ActivityLevel_n96(_uploadFile, _downloadFile, value.activity_level),
        diet_type: value.diet_type ? candid_some(to_candid_DietType_n98(_uploadFile, _downloadFile, value.diet_type)) : candid_none()
    };
}
function to_candid_variant_n104(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanStatus): {
    trial: null;
} | {
    premium: null;
} | {
    free: null;
} {
    return value == PlanStatus.trial ? {
        trial: null
    } : value == PlanStatus.premium ? {
        premium: null
    } : value == PlanStatus.free ? {
        free: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JourneyTaskType): {
    meal: null;
} | {
    water: null;
} {
    return value == JourneyTaskType.meal ? {
        meal: null
    } : value == JourneyTaskType.water ? {
        water: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnergyLevel): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == EnergyLevel.low ? {
        low: null
    } : value == EnergyLevel.high ? {
        high: null
    } : value == EnergyLevel.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    pending: null;
} | {
    refunded: null;
} | {
    success: null;
} | {
    failed: null;
} {
    return value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.refunded ? {
        refunded: null
    } : value == PaymentStatus.success ? {
        success: null
    } : value == PaymentStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietaryPreference): {
    non_vegetarian: null;
} | {
    vegetarian: null;
} {
    return value == DietaryPreference.non_vegetarian ? {
        non_vegetarian: null
    } : value == DietaryPreference.vegetarian ? {
        vegetarian: null
    } : value;
}
function to_candid_variant_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Goal): {
    muscle_gain: null;
} | {
    lifestyle_balance: null;
} | {
    fat_loss: null;
} {
    return value == Goal.muscle_gain ? {
        muscle_gain: null
    } : value == Goal.lifestyle_balance ? {
        lifestyle_balance: null
    } : value == Goal.fat_loss ? {
        fat_loss: null
    } : value;
}
function to_candid_variant_n97(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityLevel): {
    intense: null;
} | {
    light: null;
} | {
    sedentary: null;
} | {
    moderate: null;
} {
    return value == ActivityLevel.intense ? {
        intense: null
    } : value == ActivityLevel.light ? {
        light: null
    } : value == ActivityLevel.sedentary ? {
        sedentary: null
    } : value == ActivityLevel.moderate ? {
        moderate: null
    } : value;
}
function to_candid_variant_n99(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietType): {
    veg: null;
} | {
    non_veg: null;
} {
    return value == DietType.veg ? {
        veg: null
    } : value == DietType.non_veg ? {
        non_veg: null
    } : value;
}
function to_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<EditableMeal>): Array<_EditableMeal> {
    return value.map((x)=>to_candid_EditableMeal_n26(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
